### PR TITLE
Fix hanging playback when no stream is available

### PR DESCRIPTION
**Pull request by sferra**
Addresses #1560.

I can add test coverage for the new code if this solution is generally accepted.

### CODE REVIEW

**Comment by sferra** [comment]
Sorry it's taking so long, but I don't have much time and have quite some issues getting the tests green, even if the change (coincidentally) works in practice. Failing to resolve stream URLs causes an avalanche of updates to the queue, also the current logic for searching streams is hard to test and possibly not adequate for such cases. I might have to make additional changes, a thing which I initially tried to avoid. I would be grateful for any advice on how to move this PR forward, @nukeop .

**Comment by nukeop** [comment]
No problem, maybe it'll be easier if I do it for you?

**Comment by sferra** [comment]
I don't mind if you take over. 

I assumed that `PlayerBarContainer` hook `useStreamLookup` should to be called each time an invalid track stream is removed.  This might have been incorrect.

Here's what I found so far:
* In the `PlayerBarContainer` hooks, `useStreamLookup`, there's a check which prevents state propagation (`!isStreamLoading`) when removing invalid track streams (the reason the test is currently failing).
* Unconditionally dispatching "track is loading" events while removing invalid track streams creates event loops. Adding a simple check for not re-dispatching "track is loading" prevents the loops.
* We should probably not attempt to resolve the tracks again if we remove an invalid stream.

Please let me know what you find out, even if it's not the final solution.

**Comment by sferra** [comment]
Here's my local WIP state if you are curious and want to take a look: https://github.com/sferra/nuclear/pull/1

BTW, local tests for the app module seem to run indefinitely, even for "master". I don't know why. Do you have a hint?

**Comment by nukeop** [comment]
Ok, please go ahead. And I might add some sort of a check for missing fields so that these actions fail instead of hanging.

**Comment by nukeop** [comment]
I see that you added me to your fork as a collaborator. But actually, you only have to open a PR here, and Github will let me push directly to your branch (unless you explicitly forbid it). I'll take a closer look at this today.

**Comment by sferra** [comment]
Thanks, for the feedback and assistance. There's no hurry from my side. 
I'm slow to progress these PRs myself, since I have so little time.

Regarding the fork, I added you as a collaborator to the fork so you can comment and review the linked "[WIP PR](https://github.com/sferra/nuclear/pull/1)" more easily. The PR (which is now merged into this one) was within the fork, against the  branch of this PR so it contained just the diff to this PR. I just wanted to provide you with a convenient way to verify those changes.

Regarding this PR, I suppose that I should add unit test coverage to the functions I extracted, since the coverage didn't increase with this PR. The component tests cover just specific use cases and it's not possible to cover all combination of execution paths with that type of test. I understand that you prefer the component tests, but IMO it's better to have both. Unit tests help a lot in preventing regressions when making bigger changes or refactoring. They also keep the code tested as it moves between the use cases. And I don't mind writing them. : )

**Comment by nukeop** [comment]
I'm fine with this amount of coverage to be honest. The functionality you added is covered. Do you want to add anything else, or can this be merged?

**Comment by sferra** [comment]
You can merge if you feel it's safe enough. Thanks.

**Comment by nukeop** [comment]
Awesome, thanks for contributing.

**Pull request merged**
