### PR TITLE
Fixed #1423

### LINKED ISSUE #1423: Cannot drag mini-player
**Platform:**

nuclear-fd06a3, Windows 10

**Description of the issue:**

Title bar cannot be dragged in Windows 10. I cannot move the mini-player window. I don't know about other operating systems.

At 800 pixels wide, you can drag the upper right corner of the window. (orange in the image below) At 300 pixels wide, there is no draggable area.

image

### PR DESCRIPTION
**Pull request by SamarthBagga**
#1423 
Added the drag functionality to the entire navbar using this-
[link to electronjs docs to change draggable area](https://www.electronjs.org/docs/latest/tutorial/window-customization#set-custom-draggable-region)
Also made the div containing the window control buttons not draggable so that the drag functionality doesnt supersede the resize functionality.

### CODE REVIEW

**Comment by nukeop** [comment]
Doesn't matter, this is just the windows build.

**Comment by SamarthBagga** [comment]
@nukeop Thank you for the clarification. Is the rest of the code upto the standards?

**Comment by nukeop** [comment]
Yep, thanks for contributing!

**Comment by nukeop** [comment]
I'm reverting this, this causes the search bar to be unusable. Anything left of window controls can't be clicked. Did you even test it manually?

**Comment by SamarthBagga** [comment]
Hi @nukeop apologies for the oversight, I will look into it and fix the problems. I'll open another pr for this.

**Pull request merged**
