### PR TITLE
Add play next functionality

### LINKED ISSUE #476: [Feature Request] Play next button
### An option to insert a song to play next on the queue

Let's say you already have a queue of multiple songs, and you want to have a song you searched to be the next song to play.

Instead of either hitting Play Now and clearing the queue in the process, or adding to the queue and dragging it to the top I'd like to propose a play next button!

1. Click on the song
2. Select play next button in the popup menu
3. Voila

### PR DESCRIPTION
**Pull request by Tarotato**
closes #476 

- Add the actions and reducers
- Created a button in the pop up ( I assumed it was in the track popup container )

### CODE REVIEW

**Comment by nukeop** [comment]
Looks good, and I think it's alright to merge. However, does this do what you wanted? I think it will add the track to the very beginning of the queue, which will not cause it to play next, unless you're at the last song and have enabled looping.

**Comment by Tarotato** [comment]
Oh I see, I don't think that is. Would you be able to point me in the right direction?
(I also be seeming to stuck on the loading screen now too)
image

**Comment by nukeop** [comment]
What's in the console? Were you able to run it previously?

**Comment by Tarotato** [comment]
I have a duplicate Id
image

**Comment by nukeop** [comment]
Right, I fixed that on master already. You can replace 'id' with 'cs' and it should work. Or just pull from master.

**Comment by Tarotato** [comment]
Now I have an issue with bluebird, do you know what is wrong?
image

**Comment by nukeop** [comment]
Change the dependency in `packages/app/package.json` to `"bluebird": "3.5.3",`, apparently it has helped someone.

**Comment by Tarotato** [comment]
@nukeop Hi, I've updated the logic for play next - let me know if it's correct!

**Comment by nukeop** [comment]
Thanks for the update, I'll check later today;

**Pull request closed without merging**
