### PR TITLE
Unauthorized Use of Copyrighted Code and Request for Immediate Action

### PR DESCRIPTION
**Pull request by nukeop**
Since issues are disabled, I am opening a PR to address this.

This repository has unlawfully relicensed code for which I hold the copyright under public domain, without authorization. This misrepresentation not only violates my rights but also misleads the public regarding the proper licensing.

I demand that you immediately close and delete this unauthorized fork. Failure to comply will result in further legal action, including a DMCA takedown, and potential liability for damages.

### CODE REVIEW

**Comment by davidsenk** [comment]
Oh wait, you're serious? [Let me laugh even harder.](https://www.youtube.com/watch?v=_n5E7feJHw0)

You, not me, *you* said, and I quote: "In the real world nobody cares about licenses, people copy code verbatim from wherever they can find it"

https://github.com/WinampDesktop/winamp/issues/56#issuecomment-2373990939

*You* also said: "A license is not like the laws of physics. ... you can just do it without caring what words there are in a text file somewhere."

https://github.com/WinampDesktop/winamp/issues/56#issuecomment-2373753032

Additionally, *you* said: "Ignore the license and do whatever you want. "

https://github.com/WinampDesktop/winamp/issues/56#issuecomment-2373654316

Then, when called out on it, **you** doubled down on it. When I made a, somewhat sarcastic, remark that I'd make an ad-laden closed source version, **you** said "Do it, I don't care" 

https://github.com/WinampDesktop/winamp/issues/56#issuecomment-2375287354

So... *I did*.

For someone that doesn't think licenses mean anything, this is absolutely hilarious. 

I already told you that your exact comments would be used as evidence in court (when you inevitably cry about it, like you are now):

https://github.com/WinampDesktop/winamp/issues/56#issuecomment-2375295452

Do you really want to keep going down this path? Do you *really* want to make a false DMCA claim? *You, in writing* gave me permission to re-release nuclear. 

You have an absolutely laughable understanding of the law, and how open source licenses actually work. For whatever reason, you also cannot understand that *you* gave away license to your code, to me, in such a way that *you* allowed me to do whatever I'd like to do with it.

*You* made all of these choices, *you* did all of these actions, *you* need to come to terms with your own actions, and the consequences of making them.

Want me to take my repo down? I'll do it, one condition - In writing, in the readme for nuclear, as well as in the app itself (on launch), in a minimum of 24 point font, state "I, nukeop, made a blatantly stupid statement that open source licenses don't matter. I am apologizing to the open source community. Open source licenses are an important part of the open source community, and I will respect and follow all open source licenses." Keep this statement in the readme and the app in perpetuity, referencing this specific comment. Ever take it out? CC0 repo is going to come right back.

For bonus points, edit some clownhair on to your profile picture. You clearly are one.

With love,
@davidsenk

**Comment by nukeop** [comment]
The next step is a DMCA takedown and a leter from a lawyer. Refuse to comply at your own peril.

**Comment by davidsenk** [comment]
If you make a DMCA takedown I will *absolutely* make a counterclaim against you.

I made a simple request, acknowledge that *you* made a blatantly stupid statement about opensource licenses. That's it, that's all I'm asking for.

You made the decision to give your license away to me under terms outside of the AGPL. That's your problem, not mine. I will absolutely defend my right to nuclear, and my right to re-release it under CC0.

**Comment by nukeop** [comment]
If a copyright owner can show that the infringement was willful, the court may increase statutory damages up to a maximum of $150,000 per work infringed. A court will easily rule in my favor in any copyright infringement case, because you're currently documenting that you're doing this willfully. Is it really worth getting in serious debt over? This is not a joke and I intent to pursue this to the furthest extent permissible by the law.

**Comment by davidsenk** [comment]
Good lord, you're really doubling down on this.

What's so hard about admitting that you made really dumb statements about open source licenses?

What's so hard about admitting that *you* gave away your license. It's in writing. By you. 

A court will absolutely not "easily rule in your favor" 

Now please, stop asking ChatGPT, Esq. for legal advice, and just do the world a favor, admit that you were wrong, and we can all move on.

Alternative settlement offer: $1,000 USD donation to one of the following: Electronic Frontier Foundation, Open Source Initiative, Linux Foundation, Apache Software Foundation, Internet Systems Consortium, FreeBSD Project, OpenBSD Project, or any other well-known open source project that you are not affiliated with.

**Comment by nukeop** [comment]
I will allow 72 hours for compliance. In case of non-compliance after this grace period, I will be enforcing my copyright via the routes delineated above.

**Comment by davidsenk** [comment]
Settlement offer still stands.

Admit you made dumb statements, or make a $1,000 donation as described previously.

**Comment by nukeop** [comment]
To make matters abundantly clear, your right to redistribute, and/or modify this software under the terms of AGPL-3.0 is void. I also clarify that any statements I have made that you might be construing to mean that you were allowed to relicense this software under any license other than AGPL-3.0 do not mean so.

Section 8, `Termination`, of the Affero GPL 3.0 license states

>   You may not propagate or modify a covered work except as expressly
provided under this License.  Any attempt otherwise to propagate or
modify it is void, and will automatically terminate your rights under
this License (including any patent licenses granted under the third
paragraph of section 11).

Therefore your right to distribute and/or modify the software is explicitly terminated. If you do not cease to redistribute the software in this manner, you are committing a copyright violation. A licensee is not allowed to modify the license and only the copyright holder is allowed to release a covered work under a different licens. I hope that is clear to you now.

**Comment by realeatham** [comment]
You can't void it unless you explicitly said that when licensing (which you did not) afaik (Disclaimer: I am not a lawyer.)

**Comment by realeatham** [comment]
Also, their right to redistribute under aGPL may be void, but you gave permission for @davidsenk to relicense it.

**Comment by nukeop** [comment]
The code has always been available only under AGPL-3.0. Any party other than the copyright holder cannot change the license. Trying to construe an internet argument as a permission to relicense is not going to end well for the copyright violator.

**Comment by realeatham** [comment]
Maybe, I don't know law. However, you giving David permission was done basically the same as how you originally licensed it, buy saying on github that it was licensed agpl vs saying on github that David had permission to relicense. No contracts were done in either case.

**Pull request closed without merging**
