### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by nukeop**

### CODE REVIEW

**Comment by Venryx** [comment]
My poor email: XD

**Comment by nukeop** [comment]
Sorry, didn't realize this was happening. There is a setting to "reduce the number of pipelines" which should also submit everything in one commit at most once every 24h. I'll try to use that.

**Comment by nukeop** [comment]
https://support.crowdin.com/configuration-file/#configuration-file-for-vcs-integrations

Won't work here. Looks like the only way is to unsubscribe from this thread.

**Comment by Venryx** [comment]
I don't actually mind it (my email client allowed batch mark-as-read), just found it kinda funny.

**Pull request merged**
