### PR TITLE
Left hand menu tests

### LINKED ISSUE #387: Create Enzyme tests for all major views
We need to create some tests that will let us at least test if all the major views render correctly with some mocked data. This will let us avoid regressions that keep happening recently. This will likely be implemented in parts as there are many different views that need to be safeguarded like that.

"Good first issue" applies to any number of tests, even if it's just one small test for one component.

### PR DESCRIPTION
**Pull request by karlmarxlopez**
Fixes #387

### CODE REVIEW

**Comment by nukeop** [comment]
Hi, thanks for the contribution!
I think you committed wrong files. Could you please check again and revert the changes to the icons?

**Comment by karlmarxlopez** [comment]
Hi @nukeop , I've removed the build icons. But CI is still failing, sorry this is my first PR

**Comment by nukeop** [comment]
Don't worry about CI for now, that's actually my fault. I'll fix this later today and then we'll see if your tests are ready to be merged. Thanks for the update!

**Comment by nukeop** [comment]
Great job , I'm gonna merge your contribution. Before we do that, I have one small request: could you please remove the images and yarn.lock from the commit just for tidiness? If it keeps adding the images automatically, you can either edit .gitattributes, or delete it altogether (but without committing that).

**Comment by karlmarxlopez** [comment]
Hi @nukeop, are you referring to the build icons? I've already removed it.

**Comment by nukeop** [comment]
Yes, but the changes are still in PR (you removed the files and committed the removal). Could you instead use git reset to revert changes made to those icons? If you can't do that then I guess I could do that for you manually if you prefer.

**Comment by karlmarxlopez** [comment]
Hi @nukeop, I think it's better for you to do it manually. I'm afraid I might damage the repo. Sorry 😅

**Comment by nukeop** [comment]
Ok, no problem. Thanks for contributing!

**Pull request merged**
