### PR TITLE
Fix drag freezing issue when run from command line

### PR DESCRIPTION
**Pull request by qualitymanifest**
Closes https://github.com/nukeop/nuclear/issues/159

Used workaround from https://github.com/electron/electron/issues/12820#issuecomment-387798184

Dragging now works without issue when app is run from any `npm run electron:*` command. Tested using Linux Mint 19 (Ubuntu 18.04).

Per this comment https://github.com/electron/electron/issues/12820#issuecomment-452702533 this issue may be fixed in electron 3.0.14. If/when electron gets updated in this app, you can probably remove the `--disable-gpu` flags. Since that would likely require dealing with some breaking changes, this should work for now.

### CODE REVIEW

**Comment by vilanz** [comment]
For some users, the --disable-gpu option fixes issues with Linux (glibc specifically) and the project's Electron version

**Comment by nukeop** [comment]
Disabling GPU rendering altogether just to work around an Electron bug seems too drastic.

**Comment by nukeop** [comment]
Maybe I'll add this as a debug option to be enabled by users should they so wish, I don't like the idea of disabling GPU rendering everywhere in all cases because of a bug.

**Comment by qualitymanifest** [comment]
Fair enough, makes sense. Do you want me to close this? This is one of my first PRs so I'm not really sure what the proper etiquette is here.

**Comment by nukeop** [comment]
I'll keep it open for some time so I don't forget to implement this. Thanks for the help either way, at least you found out how to fix this issue. I'll try updating electron to v4 first too.

**Comment by nukeop** [comment]
I added this as an option in https://github.com/nukeop/nuclear/pull/190

**Pull request closed without merging**
