### PR TITLE
[Feature] Track Matching

### PR DESCRIPTION
**Pull request by Demizo**
Improved Youtube heuristics to make playing the correct track more consistent

### CODE REVIEW

**Comment by nukeop** [comment]
Could you please reset package-lock.json for this PR so that the diff is smaller?

**Comment by nukeop** [comment]
I'm gonna start writing tests now. There are 2 worrying failures:

- Searching for `artist: 'Nick Cave & The Bad Seeds', title: 'The Mercy Seat'`, it selects `Johnny Cash - The Mercy Seat` over `Nick Cave - The Mercy Seat`, all other things being equal
- Searching for `artist: 'The White Stripes', title: 'Seven Nation Army'`, it prefers `The Whte Stipes - Sevn Natn Ary` over `The Whte Stripes - Sevn Nation Army`.

I'm gonna see if I can fix these test cases while still preserving your new rules.

**Comment by nukeop** [comment]
Ok, I added back the title score but weighed it lower, so that it only decides if all else is very similar. Otherwise looks like all of your changes are weight adjustments, so they're covered by existing tests and don't need to be covered again. Would you like to merge this now?

**Comment by Demizo** [comment]
I'll test it quick. I have a playlist of varied music I was validating against (it had a few songs that didn't play nicely with title score so I will see if the new weights work)

**Comment by Demizo** [comment]
I didn't see any major issues with the title score added back at low weight (only a few music videos where it would have previously been the official track). Should I leave in the hacks for preventing undefined tracks?

**Comment by nukeop** [comment]
Sure, it will stop being a problem when ytdl-core is updated, but it can stay until then.

**Comment by Demizo** [comment]
Sounds good! Thanks for all the help!

**Pull request merged**
