### PR TITLE
fix: fix typo due to last refactor

### PR DESCRIPTION
**Pull request by charjac**
fix#346 
I think i catch 'em all :)

### CODE REVIEW

**Comment by nukeop** [comment]
awesome, thanks for a quick fix. I like this style of destructuring props right in the function arguments, I think I will use it from now on.

**Comment by charjac** [comment]
:) dont merge it right now i forgot to add new french translation

**Comment by nukeop** [comment]
Yeah I noticed. I will wait until you're finished.

**Comment by nukeop** [comment]
Btw, do you know if there's a way to check if a translation is complete when compared to the list of english strings? We could add a check like that to the tests too.

**Comment by charjac** [comment]
good idea !! jest + enzyme seems to be the good test stack or do you prefer mocha ?

**Comment by charjac** [comment]
i think we are good now

**Comment by nukeop** [comment]
We already have enzyme and mocha along with some really basic tests. Feel free to add Jest for new tests if you feel more comfortable with it though, I don't think it's going to mess anything up.

**Comment by charjac** [comment]
no mocha is cool (and fast) and tha api are almost the same.

**Comment by charjac** [comment]
its ready to merge (i think)

**Pull request merged**
