### PR TITLE
Fixed conditional to handle after song has been played

### PR DESCRIPTION
**Pull request by dejesusj**
I've changed the second conditional in handleFinishedPlaying to continue to select songs as long as the queue is not empty, rather than until the last song in the queue is selected. This fixes the issue mentioned in https://github.com/nukeop/nuclear/issues/677, however if shuffle is toggled and the song that is selected randomly is the one that just played, playback is paused. I believe this is related to the issue mentioned in https://github.com/nukeop/nuclear/issues/475.

### CODE REVIEW

**Comment by nukeop** [comment]
This will cause the queue to keep playing even if we're not shuffling, which should be enabled only if we use the setting `loopAfterQueueEnd`.

**Comment by dejesusj** [comment]
> This will cause the queue to keep playing even if we're not shuffling, which should be enabled only if we use the setting `loopAfterQueueEnd`.

Ah, I see. So if we're shuffling, then we want to keep picking songs at random from the queue indefinitely? And if we are not shuffling, then we want to pause playback once the last song in the queue is played?

**Comment by nukeop** [comment]
Yes, exactly.

**Comment by nukeop** [comment]
Thank you, works well now!

**Pull request merged**
