### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by kazimierczak-robert**
Update polish translation based on actual version of  "en.json"

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks for the update. There's some parsing error involving that json file, could you fix it?

**Comment by SjefVelthuizen** [comment]
unsubscribe

Op 1 september 2019 15:19 uur schreef nukeop <notifications@github.com>:



Thanks for the update. There's some parsing error involving that json file, could you fix it?

**Comment by SjefVelthuizen** [comment]
unsubscribe

Op 1 september 2019 12:04 uur schreef kazimierczak-robert <notifications@github.com>:


You can view, comment on, or merge this pull request online at:

  https://github.com/nukeop/nuclear/pull/465

Commit Summary
Update polish translation
File Changes
M app/locales/pl.json (42)
Patch Links:
https://github.com/nukeop/nuclear/pull/465.patch
https://github.com/nukeop/nuclear/pull/465.diff

**Comment by kazimierczak-robert** [comment]
Yes, there was missing comma. Now it should be right

**Pull request merged**
