### PR TITLE
Fix the website  text color same as the background 

### PR DESCRIPTION
**Pull request by sudoliyang**
fix the text color same as the background color

### CODE REVIEW

**Comment by nukeop** [comment]
Could you please take a screenshot of the element in question?

This is what it's supposed to look like:

screenshot

Is your browser overriding some css settings and changing the input field background to white?

**Comment by sudoliyang** [comment]
Hi 
On my laptop look like this 


macOS Version 10.12.4 (16E195)
Google chrome Version 57.0.2987.133 (64-bit)

**Comment by sudoliyang** [comment]
You are correct！
My Google Chrome have default `user agent stylesheet`


Change the input field background color to `transparent` can resolve this problem.

**Comment by nukeop** [comment]
Nice, it seems to work on other browsers too. If you'd like to make this change and commit, then I will merge everything. Thanks for the help.

**Comment by sudoliyang** [comment]
Yes, I had already finish this commit. 😃

**Pull request merged**
