### PR TITLE
Modified desktop file.

### PR DESCRIPTION
**Pull request by mikelpint**
I don't know if it is fine because my computer didn't let me build it.

### CODE REVIEW

**Comment by nukeop** [comment]
It should be fine, but you also changed the versions of some packages. Could you remove that part? I update packages every now and then myself, but every time I have to test if everything keeps working as before, so I'd rather not do it right now.

**Comment by mikelpint** [comment]
OK

**Comment by mikelpint** [comment]
Fixed.

**Comment by nukeop** [comment]
Hm, there are still some changes in package.json. If you leave only the changes after line 120, it'll be good.

PS. If you can't build it on your PC, check travis output (in this case it looks like it builds fine!)

**Comment by mikelpint** [comment]
I think that it is fine now. Good night anyway.

**Comment by nukeop** [comment]
Yep that's perfect. I can merge now, thanks for your help.

**Pull request merged**
