### PR TITLE
fix: Don't show empty tab in result after searching

### LINKED ISSUE #997: Don't show empty tab in result after searching
image

### PR DESCRIPTION
**Pull request by rbrishabh**
fixes #997
Hey @HaiDang666!
how does this look?
let me know if this needs any changes! Thanks

### CODE REVIEW

**Comment by nukeop** [comment]
If there are no search results in any tab, the screen will be empty. Can you add some sort of an empty state component in that case? I think we already have something like this (search for `EmptyState`).

**Comment by nukeop** [comment]
Please also write a test for this

**Comment by rbrishabh** [comment]
Hello @nukeop! I have added an empty state. I would be happy to write a test case! Is there any docs around how I can add a new test case? 
Thanks!

**Comment by HaiDang666** [comment]
You can refer from this `packages/app/app/containers/DashboardContainer/DashboardContainer.test.tsx`

**Comment by rbrishabh** [comment]
hi! I have a busy schedule and cant keep up with this now! Please feel free to continue it from here. I can close it for now

**Pull request closed without merging**
