### PR TITLE
added rename Playlist functionality

### PR DESCRIPTION
**Pull request by YajanaRao**
Added Rename playlist functionality. It is based on #283 

- Button to rename the playlist
image

- Dialog box to input the name
image

- Success Notify Message
image

Please give your suggestions

### CODE REVIEW

**Comment by YajanaRao** [comment]
Renaming the Playlist is sometime clearing all the playlist from the config.json with error message:
```
SubError {0: Error: Unable to get the lyrics with wikia.com
    at http://localhost:8080/bundle.js:197910:25, 1: Error: Unable to get the lyrics with lyricsmania.com
    at http://localhost:8080/bundle.js:197910:2…, 2: Error: Unable to get the lyrics with paroles.net
    at http://localhost:8080/bundle.js:197910:25, length: 3, message: "aggregate error", name: "AggregateError", stack: "↵AggregateError of:↵    Error: Unable to get the l…rror: Unable to get the lyrics with paroles.net↵↵", __stackCleaned__: true}
```

**Comment by YajanaRao** [comment]
I had some issue when multiple playlists are created. I have resolved it. Please do review and let me know the suggestions

**Comment by nukeop** [comment]
I will review this PR soon, thanks for the help.

**Comment by nukeop** [comment]
Very good, I only have one minor thing to request to be changed and we can merge.

**Comment by Yajan** [comment]
Sure

**Comment by YajanaRao** [comment]
Okay

**Comment by nukeop** [comment]
Added separately

**Pull request closed without merging**
