### PR TITLE
feat(i18n): integrate i18next

### PR DESCRIPTION
**Pull request by charjac**
fix#268
- internationalization using [i18next](https://www.i18next.com/)
- fix a lot of eslint warning
- refactor some class component into functionnal component when possible.

### CODE REVIEW

**Comment by nukeop** [comment]
Wow, a ton of work done, great.

However, now when I add a new feature that has new strings, I will need somebody to translate that to French (and possibly more languages in the future). Or will this pick up the default English strings if French ones are unavailable?

In any case, thanks for this awesome contribution.

**Comment by charjac** [comment]
there is a new npm script dedicated to that.
```
npm run i18n
```

**Comment by nukeop** [comment]
Ok, I see there's a fallback language set too. This will surely help all the French users, of which there are many (for some reason Nuclear is really popular in France).

**Comment by charjac** [comment]
this [guy](https://korben.info/) talk about nuclear a few months ago and he has a pretty large audience. (he is a cool hacker).
Maybe it is one of the reason.

**Comment by charjac** [comment]
maybe i should write some docs to explain all the things to do in order to add a language.

**Comment by nukeop** [comment]
I think it's pretty obvious, thanks to the self-explanatory code you wrote. We'll see if people translating the program will have any problems in the future. I'll create an issue for further translations to makeit known that translations are also very welcome as contributions.

**Pull request merged**
