### PR TITLE
Simplify Discord RPC code

### PR DESCRIPTION
**Pull request by nathanfranke**
And make it more elegant

Follow-up to #694 

**DRAFT**: I still want to simplify this more! The current workflow still uses `trackPauseTime` and it's super ugly. \
I need help from @nukeop \
What is the best way to get the currently playing song globally along with elapsed time?

### CODE REVIEW

**Comment by nathanfranke** [comment]
rest in piece. Can I get help with this question? If so, perhaps we can reopen this and I can fix merge conflicts?
> What is the best way to get the currently playing song globally along with elapsed time?

**Comment by nukeop** [comment]
Sorry, I was cleaning up old stuff globally and you got caught with the rest. The current song can be accessed in the frontend by getting `queue.queueItems[queue.currentSong]` from the redux store (preferably by using a selector), and it also sends queue updates to the main process via IPC.

**Comment by nathanfranke** [comment]
Is `queue` globally accessible? If not, should I save it from a function argument I assume?

**Comment by nukeop** [comment]
In the React part, you can access it from anywhere with `useSelector`, or pass it down from a container that uses `useSelector`.

**Comment by nathanfranke** [comment]
Still WIP, I can't seem to play songs in master though (Just shows zero duration, even without this PR). Not sure if this is reported or not

**Comment by nukeop** [comment]
All of them? Or just occasionally?

**Comment by nathanfranke** [comment]
I tried about 5 songs, none of them worked (From search not favorites)

**Comment by nukeop** [comment]
Try the newest release, music plays fine for me.

https://github.com/nukeop/nuclear/issues/834

I think this can also be fixed by this PR

**Pull request closed without merging**
