### PR TITLE
Typescript: Navbar migrated

### PR DESCRIPTION
**Pull request by Gauravsharma-20**
`packages/app/app/components/Navbar` migrated to Typescript

### CODE REVIEW

**Comment by Gauravsharma-20** [comment]
Can you please mark my PRs with `hacktoberfest-accepted` label.

**Comment by nukeop** [comment]
Due to Hacktoberfest we will no longer be accepting trivial PRs

**Comment by Gauravsharma-20** [comment]
can I still help with migration to Typescript of complex components regardless of Hacktoberfest?

**Comment by nukeop** [comment]
Sure, we'd just like to avoid one or two line PRs. We'd rather do those conversions in bulk

**Pull request closed without merging**
