### PR TITLE
Add translation portuguese brazil

### PR DESCRIPTION
**Pull request by JoaoPedroMoraes**
In this pull request the Portuguese translation of Brazil was added.

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks a lot! This will help a lot of users.

**Comment by nukeop** [comment]
You've got a type there, please fix it.
https://travis-ci.org/nukeop/nuclear/jobs/548886509#L797

**Comment by nukeop** [comment]
Did you close this by mistake?

**Comment by JoaoPedroMoraes** [comment]
> Você fechou isso por engano?


Yes, I accidentally clicked

**Pull request closed without merging**
