### PR TITLE
Make Seekbar Container More Visible

### PR DESCRIPTION
**Pull request by 1yzo**
#### Problem
- I am having a lot of trouble putting my cursor on the seekbar when trying to skip through songs.
#### Solution
- I went ahead and changed the `seekbar_container` background color to make it more visible.
- I used the same background color used for the `volume-slider-container`.

### CODE REVIEW

**Comment by nukeop** [comment]
This is a pretty standard design, the seekbar is supposed to be invisible until you play something. If you need to click it, the cursor changes to a pointer when you hover over it. Could you post a quick screenshot of your change before we decide to merge?

**Comment by 1yzo** [comment]
image

**Comment by nukeop** [comment]
Looks neutral enough, I don't have strong feelings either way.

**Comment by 1yzo** [comment]
Cool, thanks. It just always takes me a significant amount of time to get the pointer to actually show up 😂.

**Pull request merged**
