### PR TITLE
Fix - #1582 - Canceling importing JSON

### PR DESCRIPTION
**Pull request by BMischley**
Fixing #1582 

Created default value and check to no longer create error shown in issue.

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks, looks ok. It would be nice to have a test for this, do you think you could write one?

**Comment by BMischley** [comment]
Sure @nukeop . I have finished writing a test, but am having issues actually running the test/verifying the test works.  It appears they are failing to run, any ideas?  Additionally, would PlaylistsContainer.test.tsx be the best location for this test?

Thanks!
Screenshot 2024-04-24 at 6 52 18 PM

**Comment by nukeop** [comment]
Looks like a wrong type somewhere. Your editor should highlight wher eit occurs (line 55?)

**Comment by BMischley** [comment]
Interesting... I didn't edit anything in any of those files. I'll do a bit of digging.

**Comment by BMischley** [comment]
@nukeop is there anything else you'd suggest I do?

**Comment by nukeop** [comment]
Everything looks great, thank you!

**Pull request merged**
