### PR TITLE
Adds Arch Linux package.

### PR DESCRIPTION
**Pull request by mikelpint**
I don't know why the fonts are changed. Every time I do a git clone from the repository nukeop/nuclear they appear like that.

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks. Can you remove the fonts from your commit? I would like to avoid changing unrelated files.

**Comment by mikelpint** [comment]
Every time I clone the repository that happens and I don't know why.

**Comment by mikelpint** [comment]
I will fix that later.

**Comment by nukeop** [comment]
Cool. In the new version fonts are loaded differently (as needed when building) so you won't run into this problem in 0.4.0 (which will be released later this year).

**Comment by mikelpint** [comment]
Ok :grinning:

**Pull request closed without merging**
