### PR TITLE
Search in playlist added

### PR DESCRIPTION
**Pull request by thaditi**
Issue Number #1022. 

Nuclear Music Player 2021-08-25 23-03-25

### CODE REVIEW

**Comment by thaditi** [comment]
Please try again else I'll create another PR.

**Comment by HaiDang666** [comment]
I didn't notice the diff in the lock file is just 1 line. I think it's fine, you don't need to make other PR.

**Comment by HaiDang666** [comment]
There are type errors 
image

**Comment by nukeop** [comment]
Btw, this should be toggled on/off with a flag just like the other track table features.

**Comment by nukeop** [comment]
Please also create tests for this feature.

**Comment by thaditi** [comment]
> There are type errors
> image

Thanks. I'll look into it.

**Comment by thaditi** [comment]
> Btw, this should be toggled on/off with a flag just like the other track table features.

Okay. I'll make the desired changes.

**Pull request closed without merging**
