### PR TITLE
MacOs media service and build improvement

### PR DESCRIPTION
**Pull request by charjac**
This Pr includes:
 - mpris equivalent services for mac & windows (not tested yet)
 - macos touchbar and windows thumbar support (wip) i am really not sure about implementing the same for unity, in my memories unity was pure shit (if you want its nothing to implement)

conditionnal build with NormalModuleReplacementPlugin (dont know how to explain that in english ...)

### CODE REVIEW

**Comment by nukeop** [comment]
Unity as in the Ubuntu desktop environment? We have mpris, we can ignore it.

**Comment by nukeop** [comment]
Can I merge it now? Window build is failing but I can fix that if you don't have the time.

**Comment by charjac** [comment]
no, actually i am discovering that windows dev ecosystem is pure shit !!!!!!! it is so hard to compile native electron extension .... i will rollback my windows change this afternoon. and ask you to test on macos ;).

**Comment by charjac** [comment]
I removed all windows related code (i leave my implem as comment, if a win10 dev want to make it works, he is more than welcome).
The only things i left in this PR : 
  - macos Mpris like implementation (not tested)
  - correct webpack config in order to only ship platform related code in the builded app.

If you could test it on mac os i would  be grateful to you.
if it works fine and its ok for you,  its ok for me to be merged.

**Comment by charjac** [comment]
I also fail at implementing windows thumbar buttons, i test everything and nothing worked ....
I need help for this one :)

**Comment by charjac** [comment]
i also leave windows dependencies in optional dependencies (to not forget)

**Comment by nukeop** [comment]
Excellent. I'm away for Christmas and don't have the mac with me, so I'll merge now and test later.
I might be able to try my luck at the windows service on a Win 7 machine I have.

**Comment by charjac** [comment]
@nukeop I just push a very little commit on master (sorry for that), there were a little problem in mac service constructor.

**Pull request merged**
