### PR TITLE
add album in youtube search terms

### PR DESCRIPTION
**Pull request by HaiDang666**
this support https://github.com/nukeop/nuclear/issues/863 when songs title the same as album title

### CODE REVIEW

**Comment by nukeop** [comment]
In the case of that Mike Oldfield album, we search for `Mike Oldfield - Platinum Platinum`, which results in the same top result: https://www.youtube.com/results?search_query=mike+oldfield+-+platinum+platinum

Instead of matching the album name, maybe it's better to take the duration into account?

**Comment by HaiDang666** [comment]
> In the case of that Mike Oldfield album, we search for `Mike Oldfield - Platinum Platinum`, which results in the same top result: https://www.youtube.com/results?search_query=mike+oldfield+-+platinum+platinum
> 
> Instead of matching the album name, maybe it's better to take the duration into account?

I was thinking about using duration but still not sure. 

FYI: the case is `Mike Oldfield - part 1: airbone` and `Mike Oldfield - part 1: airbone platinum`. Cos we already handled subtracks.
result without album: https://www.youtube.com/results?search_query=mike+oldfield+part+1%3A+airborne
with album: https://www.youtube.com/results?search_query=mike+oldfield+part+1%3A+airborne+platinum

**Comment by nukeop** [comment]
We could use a heuristic checking if the top stream has a duration longer than e.g. 60s than the track we're looking for, and if so, reject it (since streams sometimes have varying duration).

**Comment by HaiDang666** [comment]
> We could use a heuristic checking if the top stream has a duration longer than e.g. 60s than the track we're looking for, and if so, reject it (since streams sometimes have varying duration).

To get duration from stream it takes one request. So if the top stream duration doesn't match the condition we have to request for second or third stream. Imo adding album in the search term will provide more correct result for the top stream so it can reduce one request, particularly this case.

Best solution for now is we do both: adding album title and checking duration.

**Pull request closed without merging**
