### PR TITLE
Shuffle visualization preset feature #1555

### PR DESCRIPTION
**Pull request by CarlosBor**
A couple matters:

Regarding the third point of the guidelines, "If you're fixing a bug, or adding a new functionality", this *is* a new functionality, but when checking the tests for the visualizerOverlay component there are only snapshots. I've updated them, but should I add tests on it and the randomizing function I'm using or is it understood to be simple enough to be ok as it is?

Also, as it is right now, the name of the preset is stored in the "settings" slice of the redux store, I've thus added the shuffle toggle to the same slice in a similar way, is that okay or should I change it to use a new "visualizer" slice?

Besides that, the button to toggle shuffle appears like so:
image

And the shuffle happens if enabled when a track ends.

Besides that, awaiting for revision, thanks for your patience.

### CODE REVIEW

**Comment by nukeop** [comment]
Hi thanks for contributing this. I will do a review and comment in the files individually, but it would be great to have tests that reproduce the behavior of the user using this function, so something that mounts the visualizer, selects the shuffle mode, waits for the end of the current song to see if it's changed, etc. Basically everything you added in this PR.

**Comment by nukeop** [comment]
I looked at your code and I have no additional remarks. It's all great.

**Comment by CarlosBor** [comment]
Went with the pull request update rather than writing into Discord this time, should be tidier this way.

Long story short, I did manage to mock the library but I reckon that was the wrong way to go about things, I just can't get the   handleFinishedPlaying() function from the SoundContainer component to fire. I'm guessing it ultimately triggers as a response to an event fired somewhere but I'm lost regarding how to simulate the behavior and frankly I have the suspicion that there is something obvious that I'm missing.

I'd be thankful If you could take a crack at it in case it's not too much work. Otherwise I could really do with some pointers.

Thanks for your patience.

**Comment by nukeop** [comment]
Hey, I'm working on fixing the Windows build first. I'll take a look as soon as I can. I'm sure we'll figure it out together somehow.

**Comment by CarlosBor** [comment]
Sure thing. I use Windows so if I can offer any assistance I'm up for it, don't know much about the matter though.

In the meantime I'll take a small gander at #1539, will comment in that thread if I start taking care of it proper.

**Comment by nukeop** [comment]
The day has come when I finally have the time to get around to this.

**Comment by nukeop** [comment]
I managed to rewrite the tests, now everything mounts correctly, and there's a way to access the onFinishedPlaying callback to check what was passed to it. It doesn't work yet, but it's pretty close.

**Comment by nukeop** [comment]
Ok, I finished the setup. It demonstrates the way you can extract a callback from a mocked React component to call it imperatively. Would you like to add anything else, or can we merge this?

**Pull request merged**
