### PR TITLE
Start of Chinese (Simplified) Translation

### LINKED ISSUE #345: Translations (looking for contributors)
We're looking for contributors who are willing to translate Nuclear to their native languages (or any languages that they know well). Currently @charjac has done all the work required to add new translations, and also translated all the strings to French.

New locales should be placed here: https://github.com/nukeop/nuclear/tree/master/app/locales

**Languages currently available:**
- English
- French (by @charjac)
- Dutch (by @Vistaus)
- Danish (by @Hansen1992)
- Spanish (by @mlucas94 )
- Polish (by @kazimierczak-robert and @gradzka)

**Proposed:**
- Chinese (simplified) (by @lizzyd710)
- Russian (by @ramstore07)

### PR DESCRIPTION
**Pull request by lizzyd710**
This is my initial progress on the Chinese translation. I can translate more, but I wanted to submit the pull request so that Chinese could get in there sooner. In the `zh.json` file, there are a few partial translations like 
`"program-settings": "Program设置",` and `"loading": "Stream还在加载.",`. @nukeop said that even if I could only translate part of it, it would be okay, and I wanted to make sure this is what they meant.

Fixes #345

### CODE REVIEW

**Comment by nukeop** [comment]
There's a small error in the locale file, one of the strings isn't in quotes (you can see it highlighted if you look at your changes on Github), and there is also a missing comma there.

I made those changes locally and your translation works and displays fine. You should correct that and commit it, so that the changes are attributed to you, and after it works I'll merge it.

Really great work with the translation!

**Comment by lizzyd710** [comment]
Thanks! (Sorry for so many commits, I made little mistakes and then had to fix them.)

**Comment by nukeop** [comment]
No problem, I can just rebase, make however many commits you need.

One more thing though, could you please remove the changes in package.json in lines 1 and 71? Npm is not necessary as a dependency and I'm not sure what's changed in line 1 but it causes webpack dev server to fail at start.

**Comment by lizzyd710** [comment]
Yeah, sure. I was having some problems with npm when I firsts started and I think one of the commands I might have ran must have changed it.

**Comment by lizzyd710** [comment]
I didn't see any changes in line 1, but I removed the npm dependency on line 71, which was the only difference detected (besides adding Chinese to the languages).

**Comment by nukeop** [comment]
Apparently there's an invisible character before the opening brace (highlighted in red):

2019-06-17-001931_302x131_scrot

**Comment by lizzyd710** [comment]
Ah, okay. Fixed it!

**Comment by nukeop** [comment]
Thanks!

**Pull request merged**
