### PR TITLE
fix Playnext button: #1420

### PR DESCRIPTION
**Pull request by akakayan**
I fixed the issue mentioned in #1420 by put the PlayNext Song after the current song. 

This is my first time contributing to this project as well as an open source project so just tell me if there is anything else I need to do or should be fixed.

### CODE REVIEW

**Comment by nukeop** [comment]
Looks good, would you be able to add a test for this? You can use existing tests as a guide.

**Comment by akakayan** [comment]
Sure I will do that . Just want to make sure, I think I am supposed to add the test to trackpopupcontainer.test.tsx? That's the place I found where play next button is relevant. However, there is no pervious test about it so I am not sure if that's the place I should go to.

**Comment by akakayan** [comment]
Hi, I've added a test for playNext and it passed on my local machine, can you review that?

**Comment by nukeop** [comment]
Perfect, thank you fo rimplementing this.

**Pull request merged**
