### PR TITLE
Fix in installations instructions

### PR DESCRIPTION
**Pull request by uliska**

### CODE REVIEW

**Comment by nukeop** [comment]
Npm installs dependencies locally, it shouldn't require sudo, unless you clone the repository with sudo.

**Comment by uliska** [comment]
Ok, I'll post the error message that led me to that conclusion later when I'm home again.

But the other part about npm install vs. npm run install stands.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by nukeop** [comment]
Agreed, it should be `npm install`, my bad.

**Comment by uliska** [comment]
When running `npm install` the process ended with a failure, containing this in the log:

```
144898 error Linux 4.9.0-1-amd64
144899 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
144900 error node v8.0.0-pre
144901 error npm  v4.1.2
144902 error code ELIFECYCLE
144903 error nuclear@0.1.0 postinstall: `concurrently "install-app-deps" "node n
ode_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
144903 error Exit status 1
144904 error Failed at the nuclear@0.1.0 postinstall script 'concurrently "insta
ll-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.j
son"'.
144904 error Make sure you have the latest version of node.js and npm installed.
144904 error If you do, this is most likely a problem with the nuclear package,
144904 error not with npm itself.
144904 error Tell the author that this fails on your system:
144904 error     concurrently "install-app-deps" "node node_modules/fbjs-scripts
/node/check-dev-engines.js package.json"
144904 error You can get information on how to open an issue for this project wi
th:
144904 error     npm bugs nuclear
144904 error Or if that isn't available, you can get their info via:
144904 error     npm owner ls nuclear
144904 error There is likely additional logging output above.
144905 verbose exit [ 1, true ]
```

`sudo npm install` also produces warnings but succeeds installing the program

```
$ sudo npm install
npm WARN lifecycle nuclear@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) nuclear@0.1.0 concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json" /home/uliska/git/software/nuclear
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN react-tap-event-plugin@0.2.2 requires a peer of react@^0.14.0 but none was installed.
npm WARN You are using a pre-release version of node and things may not work as expected
```

So this is why I assumed that `sudo` is required.

**Comment by nukeop** [comment]
Yeah, you need the LTS version of node - currently 6.10.0.

You're using 8.0 pre-release, which is the likely culprit.

**Comment by uliska** [comment]
OK, but then the phrasing "may require root privileges" seems pretty appropriate, isn't it?
I mean, there's no specific reason to use a specific version of node.js, isn't it?

**Comment by nukeop** [comment]
Regular programs that don't need to modify anything above your /home/ directory should never require root privileges. What is likely happening here is that you have a different version of npm installed or aliased system-wide and in your local user account, that's why they work differently.

Can you run `npm --version` and `sudo npm --version` and compare the outputs?

**Comment by uliska** [comment]
Both return the sams  `4.1.2`, and `which` points to `/usr/local/bin/npm` in both cases.

But if you're convinced that it has to do with some peculiarity of my installation I won't be the one to talk you into a different opinion. My Node knowledge is pretty limited.

Anyway, I got your program to run, and on first sight it looks pretty cool. I'll have a closer look, try it out for some time and maybe come back with some features requests ...

**Pull request merged**
