### PR TITLE
This is a pull request related to Issue #1111.

### PR DESCRIPTION
**Pull request by gnsdyd12**
This is a pull request related to Issue #1111.

When I raised the window window, I modified the image to grow as it was cut off due to the media query.

When reducing the window size, the minimum window size was specified, and the mini player became too small to see the UI well, so the minimum window size was specified and improved.

### CODE REVIEW

**Comment by gnsdyd12** [comment]
There's an error, so I'm fixing it again.

**Comment by gnsdyd12** [comment]
Finished.

**Comment by gnsdyd12** [comment]
I'd appreciate it if you could write any review.

**Comment by nukeop** [comment]
Thanks, I launched it and tried a variety of sizes and songs. The only downsize is that the text gets pretty small if you make the window the smallest possible size, but overall I like this change a lot.

**Pull request merged**
