### PR TITLE
feat: add a simple express rest api to remotly control nuclear

### PR DESCRIPTION
**Pull request by charjac**
All endpoints are POST except when specified.

playlist:
 - /nuclear/playlist GET (list of playlist)
 - /nuclear/playlist { name: 'myplaylist' }
 - /nuclear/playlist/:name DELETE

queue
 - /nuclear/queue/empty
 - /nuclear/queue GET

docs:
 - /nuclear/docs  GET swagger UI (html page)
 - /nuclear/docs/swagger.json GET

player:
  - /nuclear/player/play
  - /nuclear/player/pause
  - /nuclear/player/stop
  - /nuclear/player/play-pause
  - /nuclear/player/volume { value: 50 }
  - /nuclear/player/seek { value: 50000 }
  - /nuclear/player/now-playing GET
  - /nuclear/player/mute

window:
  - /nuclear/window/maximize
  - /nuclear/window/minimize
  - /nuclear/window/quit

settings:
 - /nuclear/settings GET
 - /nuclear/settings/:option GET
 - /nuclear/settings/:option { value: true }

If this suit your need, i can add a /player/now-playing endpoint and playlist management.

#120

### CODE REVIEW

**Comment by nukeop** [comment]
wow, this is amazing, a lot of great work. I took a look at your code and don't have any remarks. I'll test it this evening and see how it works in practice, and then I'll merge it.

**Comment by charjac** [comment]
Thx :), dont merge it yet, I will add a now-playing endpoint and playlist management

**Comment by charjac** [comment]
the port used in dev is 3000 and 8080 in production

**Comment by charjac** [comment]
I can add a swagger to document the api, do you think it is necessary ?

**Comment by nukeop** [comment]
If it's low cost then sure, go ahead, but if it takes more effort then I guess we can just use the code as documentation for now, since it's pretty self explanatory and clear.

**Comment by acrisci** [comment]
I'm going to wait on #279 for this.

**Comment by charjac** [comment]
its ok for me. Maybe sould we store the api port in the settings ?

**Comment by nukeop** [comment]
yes, that sounds sensible.

**Comment by nukeop** [comment]
I tested it in practice and it works great. It could be useful to also have some endpoints for managing the queue (is that what you're doing now?). If you don't feel like implementing it, I will be more than happy to handle it myself. This lays some important groundwork for more advanced features, and opens up a whole new universe of upgrades we can implement. I'm extremely grateful and blown away by the amount and quality of work that you've done.

**Comment by charjac** [comment]
Your are welcome :) I am personally a big fan of this great app.
For the queue management, i see only 2 endpoints:
  - /queue/empty
  - /queue/playlist { name: string }

i you see others, just indicate below and i quickly implement them.

**Comment by nukeop** [comment]
I think that's all we need.

**Comment by charjac** [comment]
i also add: 
- list all the playlist
- remove a specified playlist

**Comment by charjac** [comment]
I think i am done with it.
I tried to add /nuclear/playlist/:name but i fail in the action creator addPlaylistTracksToQueue, i didnt get what musicSources is.
https://github.com/nukeop/nuclear/blob/master/app/actions/queue.js

**Comment by nukeop** [comment]
I will review this later today and probably merge it, thanks.

**Pull request merged**
