### PR TITLE
[WIP] Adding hovering and active states to the player buttons

### PR DESCRIPTION
**Pull request by hibroseph**
Going to keep updating here so you can check on what I am doing and give input as I am coding. I still need to add those styling elements to the forward and backward. 

What do you think of the styling currently on the pause button?
#286

### CODE REVIEW

**Comment by nukeop** [comment]
To keep things consistent, it's better to use colors from the palette (vars.scss), instead of directly setting colors.

**Comment by hibroseph** [comment]
Affirmative.

**Comment by nukeop** [comment]
To be clear, feel free to use scss functions like darken or rgba (to set opacity) with palette colors.

**Comment by hibroseph** [comment]
I just want to say, it took me **WAY** too long to realize that the sass operators (like the ampersand & or the color) need to have spaces. A lack of spaces between will alter their operation.

**Comment by hibroseph** [comment]
How do they look right now? Should I do an active state?

**Comment by nukeop** [comment]
You don't need to use & if you use a space.

```css
.a {
  .b { }
}
```

Is identical to
```css
.a .b { }
```

Which in both cases selects all bs inside as. However,
```css
.a {
  &.b {

  }
}
```
selects everything that has both class a and b at the same time.

**Comment by hibroseph** [comment]
What about with puesdos? Don't I need the ampersand in front of puesdos, such as

```(javascript)
&:not(.player_button_disabled) :hover {
    transition: $short-duration; 
    color: darken($white, 50%);
  }
```

**Comment by nukeop** [comment]
Yes, the ampersand is a shorthand for referring to the selector from the level above, so e.g.
```css
.a {
 &:hover { }
}
```

Refers to `a:hover`. 

The selector you created in your comment refers to any hovered-over element that is a child of an element that does not have the class `.player_button_disabled` (depending on how this is nested).

**Comment by hibroseph** [comment]
That is what I intended.

Should I be more specific in my code about the children that I can hover
over?

**Comment by nukeop** [comment]
As long as it works as you intended, it's all good.

**Comment by hibroseph** [comment]
@nukeop sorry I didn't let you know what I had done. Want to take a look at it now?

**Comment by nukeop** [comment]
Sure, I'll review soon after you commit your changes, no rush.

**Comment by nukeop** [comment]
Hi, are you still working on it, or can it be improved/finished by somebody else? Or would you rather have us not use your code?

**Comment by hibroseph** [comment]
Sorry about that! I thought I had committed my changes. Let me see where I left it at and commit those changes (if I have any)

**Comment by nukeop** [comment]
Ok, cool.

**Pull request closed without merging**
