### PR TITLE
Downgraded 'react-range-progress'

### PR DESCRIPTION
**Pull request by Chandankkrr**
Fix for failing build due to `babel preset "stage-0"`

### CODE REVIEW

**Comment by Chandankkrr** [comment]
@nukeop Running `npm run build:dist` locally builds fine with `react-range-progress` version 4.0.2 but fails in Travis CI. 

One of the possible solution is to install `babel-preset-stage-0` but it's not ideal.

Any possible solutions to fix this?

**Comment by nukeop** [comment]
Feel free to add that, no problem.

**Comment by Chandankkrr** [comment]
Ok, the issue is fixed now. I am guessing the build failure for `OSX` is a known issue?

**Comment by nukeop** [comment]
Yeah, it is. `electron-builder`-related.

**Comment by Chandankkrr** [comment]
Ok cool.

**Pull request merged**
