### PR TITLE
Play pause test

### PR DESCRIPTION
**Pull request by jenyeeiam**
My first ever PR! Suggestions welcome :)

Enzyme tests for the PlayerControl components

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks for the contribution, looks really good.
I think you forgot to add jsdom-global to dev dependencies. Do you think it's necessary for the tests to run?

Take a look here: https://github.com/nukeop/nuclear/blob/c1c671ca9ae127a6f1c774a96ab8a2a62ee67a88/test/setup.js
JSDOM is already included in test setup, maybe this will already setup the environment the way you want to?

**Comment by jenyeeiam** [comment]
Oh ya ok. I was importing jsdom because I was getting errors when I was trying to do a full DOM rendering with mount(). What's the best way to do it with this setup file?

**Comment by jenyeeiam** [comment]
Sorry! This was a result of me needing this in order to run my test individually. Making my changes now

**Comment by nukeop** [comment]
Now it's passing, thanks.

**Pull request merged**
