### PR TITLE
Update ScreenShots Links in docs/*.md Files

### PR DESCRIPTION
**Pull request by mohmadhabib**
Just update the Links from ./screenshots/* to ../screenshots/*

### CODE REVIEW

**Comment by mohmadhabib** [comment]
This PR will solve #1693

**Comment by nukeop** [comment]
Thanks for fixing the links, could you remove the unrelated changes? Looks like there's a lot of formatting being changed.

**Comment by mohmadhabib** [comment]
> Thanks for fixing the links, could you remove the unrelated changes? Looks like there's a lot of formatting being changed.

Sure, I have Just noticed the Formatting changes once you mentioned it, i will review it ASAP

**Comment by mohmadhabib** [comment]
It should be done now, Please review

i would like to thank you for this amazing project 😄

**Comment by nukeop** [comment]
Thank you, looks good.

**Pull request merged**
