### PR TITLE
Adds Arch Linux package to the list of avaliable packages.

### PR DESCRIPTION
**Pull request by mikelpint**
It is located in the .releases directory.

### CODE REVIEW

**Comment by nukeop** [comment]
Thanks, I will modify the readme later and add a section about third party packages. If you're okay with that I could list you there as the maintainer of this one.

**Comment by mikelpint** [comment]
Yes, I'm okay

**Comment by nukeop** [comment]
Do you need to add windows binaries to .releases? I'm concerned they would just take space for no good reason. I don't really know how Arch packages work so let me know if it's necessary. Might also be a good idea to remove .deb and tar.gz (appimage should work fine).

Also, you've changed some fonts for some reason.

**Comment by mikelpint** [comment]
I only need AUR and .pkg.tar.xz.

**Comment by mikelpint** [comment]
I don't know why

**Comment by mikelpint** [comment]
I will do a new pull request.

**Pull request closed without merging**
