### PR TITLE
Wrap all text in i18next functions

### LINKED ISSUE #647: Wrap all text in i18next functions
Hi!

This is somewhat related to #345 

While adding the Swedish translation I noticed that there are several texts that are hard-coded and not going through i18next. I'm not sure if you have other plans for handling translations, or if it just is low-priority in relation to other issues. But I wanted to fix it, and just continued coding after finishing the translation. :)

I have a PR that I hoped of getting feedback on. You can find it [here](https://github.com/nukeop/nuclear/pull/648).

### PR DESCRIPTION
**Pull request by St3phy831**
I was able to wrap all the hard-coded text using the i18next functions along with my teammates @odiaz95012 and @ramy-meng. We also added the keys to the different language json files so they can be translated. 

Closes #647

### CODE REVIEW

**Comment by HaiDang666** [comment]
Thanks for your contributions. Since we use Crowdin for managing translation, you don't need to update keys in all language files only need to change in `en.json`. Can you use please remove those changes?

**Comment by odiaz95012** [comment]
Absolutely! We’ll get to work on it.

**Comment by nukeop** [comment]
Great, thank you, and thanks for setting this straight.

**Comment by nukeop** [comment]
All you have to do is just revert all files in i18n that are not en.json.

**Comment by odiaz95012** [comment]
Got it! I deleted all added keys from all language JSON files except for
en.json. Just checking my work with my team.

**Comment by odiaz95012** [comment]
My team and I reverted all language JSON files back to what they were except for en.json.

**Comment by HaiDang666** [comment]
You have to update snapshot test to make the CI pass. 
image

**Comment by ramy-meng** [comment]
Hi, I am one of the members who is working on this pull request. All of us are beginner coders, could you further explain what do you mean by updating the snapshot test to make the CI pass?

**Comment by HaiDang666** [comment]
There is a test to ensure UI  render as expected, it's called [snapshot testing](https://jestjs.io/docs/snapshot-testing). When there is a modify in UI the test will fail cos it compares with the previous UI. About [CI](https://docs.github.com/en/actions/automating-builds-and-tests/about-continuous-integration), one of its jobs in nuclear is checking all tests pass in PR. In short, you need to run the test with '--updateSnapshot' key.

**Comment by nukeop** [comment]
After you run `npm test -- -u`, you have to commit and push all the changes in existing snapshots (`.snap` files).

**Comment by odiaz95012** [comment]
> After you run `npm test -- -u`, you have to commit and push all the changes in existing snapshots (`.snap` files).

Every time I run 'npm test -- -u' I get the error "ERR! lerna Unknown argument: u". Do I need to install something to make this work?

**Comment by nukeop** [comment]
Try going to `packages/app` first, the `-u` flag needs to be applied to jest instead of lerna.

**Comment by ramy-meng** [comment]
Screen Shot 2021-11-15 at 10 40 07 PM
Thank you everyone for your guidance. It seemed like I have updated the snapshot. Please help me verify one last time before I commit and push my branch.

**Comment by HaiDang666** [comment]
Nice work, one last thing that revert change in other language file

**Comment by ramy-meng** [comment]
My teammate @odiaz95012 seemed to have reverted all changes in other language files. Is there any part that we have left out?

**Comment by HaiDang666** [comment]
> My teammate @odiaz95012 seemed to have reverted all changes in other language files. Is there any part that we have left out?

Did your friend push the commit, those changes still in PR. You can see in the `file changes` tab

**Comment by odiaz95012** [comment]
> > My teammate @odiaz95012 seemed to have reverted all changes in other language files. Is there any part that we have left out?
> 
> 
> 
> Did your friend push the commit, those changes still in PR. You can see in the `file changes` tab

Yes, I pushed the changes where I got rid off all the keys we added from all language files except en.json.

**Comment by odiaz95012** [comment]
> > > My teammate @odiaz95012 seemed to have reverted all changes in other language files. Is there any part that we have left out?
> > 
> > 
> > 
> > Did your friend push the commit, those changes still in PR. You can see in the `file changes` tab
> 
> Yes, I pushed the changes where I got rid off all the keys we added from all language files except en.json. 

So our pull request should now have updated snapshots and all of our added keys are now only in en.json.

**Comment by HaiDang666** [comment]
I got it, there was a change on last line in other files. 
image

**Comment by nukeop** [comment]
The whitespace changes are fine, but it looks like snapshots do not pass, I'll check it out later today.

**Comment by ramy-meng** [comment]
Oh, no. Was it because of my snapshot? Please feel free to let us know whatever needed to be fixed.

**Comment by nukeop** [comment]
It's because the test setup for settings doesn't have internationalization enabled, I'm fixing this now.

**Pull request merged**
