### PR TITLE
Changed to TypeScript

### PR DESCRIPTION
**Pull request by Hardik-hi**
Changed index.js to TS equivalent, index.tsx  #1002

### CODE REVIEW

**Comment by nukeop** [comment]
Hi, please read the guide for converting components to Typescript: https://app.gitbook.com/@nukeop/s/nuclear/contributing/converting-to-typescript

In short, the components should have proper types and the props should be typed too.

**Comment by Hardik-hi** [comment]
> Hi, please read the guide for converting components to Typescript: https://app.gitbook.com/@nukeop/s/nuclear/contributing/converting-to-typescript
> 
> In short, the components should have proper types and the props should be typed too.

Done. Please check.

**Comment by nukeop** [comment]
Please run linter before committing changes, and fix the issues.

**Comment by HaiDang666** [comment]
your eslint issues

image

**Comment by Hardik-hi** [comment]
Hey @nukeop @HaiDang666 I have performed linter tests and build tests using npm build successfully.
Output log file is attached.

[output.txt](https://github.com/nukeop/nuclear/files/7147664/output.txt)

**Comment by nukeop** [comment]
Thanks, let's wait for the CI to finish running and we can merge it.

**Pull request merged**
