### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by 3DShark**
update tr lang

### CODE REVIEW

**Comment by nukeop** [comment]
Did you forget to commit all files?

**Comment by 3DShark** [comment]
Yes, i made json file and forgot the change package.json

**Comment by nukeop** [comment]
Ok, I'll merge when you add the missing files.

**Comment by 3DShark** [comment]
Added the files and https://github.com/nukeop/nuclear/issues/345  setting.js is not under constant its under common/setting.js

**Comment by nukeop** [comment]
Thanks, awesome contribution.

**Pull request merged**
