### PR TITLE
the api now only uses ports that are available

### PR DESCRIPTION
**Pull request by leonlafa**

### CODE REVIEW

**Comment by leonlafa** [comment]
PR made for issue:
https://github.com/nukeop/nuclear/issues/356

**Comment by nukeop** [comment]
Thanks, great contribution.

**Comment by leonlafa** [comment]
> Thanks, great contribution.

Currently has a choice of 10 ports to choose from, we can extend this functionality if needed.

**Comment by nukeop** [comment]
I think that will fix the problem we had. Looks like it builds, time to merge.

**Comment by leonlafa** [comment]
> I think that will fix the problem we had. Looks like it builds, time to merge.

Brilliant, I'll keep my eye out for other issues

**Pull request merged**
